### ISSUE TITLE
DebugMonitor is broken atm on x86_gcc2

### ISSUE THREAD

**Issue by Begasus** [HaikuArchives/DebugMonitor#2]
Build log: https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/2597/builds/31747.log
(haven't checked the x86_64 build)

**Comment by humdingerb** [comment]
Seems to me, like the DebugClient.a file is platform dependend and including the file from a x64 build breaks the 32bit build.

I suppose the recipe needs to have a 

`cp DebugClient/objects/DebugClient.a Scribble/`

after the DebugClient has been built.

**Comment by Begasus** [comment]
Ok that worked, but why include a lib from another platform, it's being build so mv/cp it to the right place could solve that?

**Comment by Begasus** [comment]
Created a fixed recipe to handle this, but I still think the DebugClient.a file should not be included in the source for Scribble but rather cp'd there right after it's build.

**Comment by humdingerb** [comment]
Agreed. I'll remove the DebugClient.a from the Scribble folder and add a hint how to build.

**Comment by humdingerb** [comment]
Fixed with 31a5d2d
